// Links and their headings stored in the array.
export let footerLinks = [
    {id: 1,
    heading: 'Women',
    links: [
        {id: 1,
        name: 'Dresser',
        link: '/pages/women/dresses/dresses.html'},
        {id: 2,
        name: 'Pant',
        link: '/pages/women/pants/pants.html'},
        {id: 3,
        name: 'Skirt',
        link: '/pages/women/skirts/skirts.html'}
    ]},
    {id: 2,
    heading: 'Men',
    links: [
        {id: 1,
        name: 'Shirts',
        link: '/pages/men/shirts/shirts.html'},
        {id: 2,
        name: 'Pants',
        link: '/pages/men/pants/pants.html'},
        {id: 3,
        name: 'Hoodies',
        link: '/pages/men/hoodies/hoodie.html'}
    ]},
    {id: 3,
    heading: 'Kids',
    link: '/pages/kids//kids.html'},
    {id: 4,
    heading: 'Links',
    links: [
        {id: 1,
        name: 'Home',
        link: '/'},
        {id: 2,
        name: 'Login',
        link: '/pages/login/login.html'},
        {id: 3,
        name: 'Contact',
        link: '/pages/contact/contact.html'},
    ]},
];